name = "airq-web"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./public"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "airq-db"
database_id = "b3d6516d-db5e-4e84-9db9-3a0c37a7d0d7"

